name: Auto-Assign Arun for DB Changes

on:
  pull_request:
    paths:
      - '**'

jobs:
  assign-reviewer:
    runs-on: [self-hosted]
    steps:
      - name: Assign Arun as  Reviewer 
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['arunsahu92']
            });
