name: azure-deploy.yml

on:
  push:
    branches:
      - main  # Deploy on push to main
  workflow_dispatch:  # Allow manual deployment
  workflow_call: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Change this based on your .NET version

    - name: Restore Dependencies
      run: dotnet restore
      working-directory: Annapurnaworld.api

    - name: Build the Project
      run: dotnet build --configuration Release --no-restore
      working-directory: Annapurnaworld.api  

    - name: Publish the App
      run: dotnet publish -c Release -o ./publish
      working-directory: Annapurnaworld.api
 
